<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model.DesignedDiffs.xafml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model.DesignedDiffs.xafml" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp.Blazor" Version="25.2.1-alpha-25302" />
    <PackageReference Include="DevExpress.ExpressApp.ConditionalAppearance" Version="25.2.1-alpha-25302" />
    <PackageReference Include="DevExpress.ExpressApp.Security" Version="25.2.1-alpha-25302" />
    <PackageReference Include="DevExpress.ExpressApp.Validation.Blazor" Version="25.2.1-alpha-25302" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="25.2.1-alpha-25302" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.2.1-alpha-25302" />
  </ItemGroup>
</Project>
